units: "config/units.tsv"

#tool configurations

#please select "diploid" for healthy samples and "uniform" for tumor samples
orthanq_prior: "uniform"

#reference conigurations
ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 25
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 111
  # Genome build
  build: GRCh38
  # Optionally, instead of downloading the whole reference from Ensembl via the
  # parameters above, specify a specific chromosome below and uncomment the line.
  # This is usually only relevant for testing.
  # chromosome: 21
